import "./globals.css";
import { SparklesText } from "@/components/ui/sparkles-text"
import { DockDemo } from "@/components/dock/dock";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="m-5" >
      <SparklesText text="Inicio" className="text-center mb-3"/>
        {children}
      <DockDemo />
      </body>
    </html>
  );
}